name = "yart-worker"
main = "src/index.ts"
compatibility_date = "2024-09-09"

[dev]
port = 8787

[[durable_objects.bindings]]
name = "ROOM"
class_name = "Room"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Room"]

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "yart-images"
